name: cyber-hammer-stack

services:
  cyber-hammer-postgres:
    image: postgres:18.3-alpine3.23
    container_name: cyber-hammer-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
      POSTGRES_USER: ${POSTGRESQL_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
    # ports:
    #   - "${POSTGRESQL_DB_PORT}:${POSTGRESQL_DB_PORT}"
    volumes:
      - cyber_hammer_postgres_data:/var/lib/postgresql
    networks:
      - cyber-hammer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  cyber-hammer-telegram:
    build:
      context: .
      dockerfile: Dockerfile.main.telegram
    container_name: cyber-hammer-telegram
    restart: always
    env_file:
      - .env
    depends_on:
      cyber-hammer-postgres:
        condition: service_healthy
    networks:
      - cyber-hammer-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cyber_hammer_postgres_data:

networks:
  cyber-hammer-network:
    driver: bridge
    name: cyber-hammer-network
