name: cyber-hammer-stack

include:
  - docker-compose-base.yml

services:
  cyber-hammer-telegram:
    build:
      context: .
      dockerfile: Dockerfile.main.telegram
    container_name: cyber-hammer-telegram
    restart: always
    env_file:
      - .env
    depends_on:
      cyber-hammer-postgres:
        condition: service_healthy
    networks:
      - cyber-hammer-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
