FROM python:3.11.9-slim-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "streamlit", "run", "01_Super_Chat.py" ]
